apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
bootstrapTokens:
- token: "yxddj3.7zcqr0inoe4v59qp"
  description: "kubeadm bootstrap token"
  ttl: "24h"
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha3
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
